[tox]
env_list = 
    py311
    py312
    py313
    py314

[testenv]
package = skip
commands = 
    pip install pytest pytest-asyncio pytest-cov python-dotenv telethon rich readchar sqlalchemy aiosqlite
    python -m pytest